### ISSUE TITLE
老哥用的哪个tf版本，能否传一下onnx

### ISSUE THREAD

**Issue by xinheblue** [Li-chunming/onnxruntime-maskrcnn#2]
如题，老哥做这个很有用，我看你上一个帖子里说用的tf转的，是哪个版本，能否传一下转好的onnx

这里有一个onnx转好了的
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn

用可视化工具看了，跟老哥代码用的这个结构差别好像比较大

**Comment by xinheblue** [comment]
用的是这个tf版本吗

https://github.com/matterport/Mask_RCNN

**Comment by xinheblue** [comment]
上面这个转换的时候，用Keras-onnx，会报错
will convert to onnx
Traceback (most recent call last):
  File "demo.py", line 133, in <module>
    onnx_model = keras2onnx.convert_keras(model, "mask")
  File "D:\software\Anaconda3520\lib\site-packages\keras2onnx\main.py", line 59, in convert_keras
    output_names = [n.name for n in model.outputs]
AttributeError: 'MaskRCNN' object has no attribute 'outputs'

**Comment by Li-chunming** [comment]
这个是keras-onnx版本和tensorflow版本冲突的原因，这两者的版本有个对应区间，tensorflow不要用2.0版本以上，keras-onnx下载github上的然后自己setup就行，或者pip安装最新版貌似也行。你先改改这俩版本试试，不行的话我过几天可以把我的版本号发给你。

**Comment by xinheblue** [comment]
尝试了多个版本组合，都有报问题

目前最新尝试的是
1，maskrcnn 用的最新代码https://github.com/matterport/Mask_RCNN
2,  tensorflow版本为1.13.2
3, keras版本为2.3.1
4,keras-onnx用的最新https://github.com/onnx/keras-onnx 的代码，然后python setup.py install的
5,导出过程为给MaskRCNN类加了一个方法
def onnx(self):
        import keras2onnx
        onnx_model = keras2onnx.convert_keras(self.keras_model)
        temp_model_file = 'model.onnx'
        keras2onnx.save_model(onnx_model, temp_model_file)
在demo.py的基础上，加载weights后，执行导出
# Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)

# Load weights trained on MS-COCO
model.load_weights(COCO_MODEL_PATH, by_name=True)
model.onnx()

还是报错，目前的报错是
ValueError: get tensor value: TFNodes/mrcnn_detection/map/while/PadV2/paddings_Concat__352 must be Const

您看下我有没有流程处理错，或者版本要怎么调一下，多谢！

**Comment by Li-chunming** [comment]
感觉还是版本问题 我把我成功的版本给你 你对比试一下：

> Keras                2.2.0
Keras-Applications   1.0.2
Keras-Preprocessing  1.0.1
keras2onnx           1.6.5               d:\keras-onnx-master
onnxruntime          1.1.2
tensorboard          1.8.0
tensorflow           1.8.0
tf2onnx              1.5.5
